steps:
#- name: 'ubuntu:trusty'
- name: 'gcr.io/spinnaker-terraform/postgres'
  #env: ['POSTGRES_PASSWORD=test1234']
  entrypoint: 'bash'
  #args: ['bash', 'workspace/postgres.sh']
  #args: ['postgres.sh']

# Building GCR image for application jar
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/postgres:latest', '-f', 'Dockerfile', '.']


#logsBucket: 'gs://cloud_builds'

#
# Uploading GCR images for application jar
#
images:
  - 'gcr.io/$PROJECT_ID/postgres:latest'

# Build timeout
timeout: 1800s
