steps:
# Building GCR image for application jar
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/postgres12:latest', '-f', 'Dockerfile', '.']


#logsBucket: 'gs://cloud_builds'

#
# Uploading GCR images for application jar
#
images:
  - 'gcr.io/$PROJECT_ID/postgres12:latest'

# Build timeout
timeout: 1800s
