#test stash example
steps:
# Building GCR image for application jar
- name: 'gcr.io/cloud-builders/docker'
<<<<<<< Updated upstream
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/pg45:latest', '-f', 'Dockerfile', '.']
=======
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/pg4:latest', '-f', 'Dockerfile', '.']
>>>>>>> Stashed changes


#logsBucket: 'gs://cloud_builds'

#
# Uploading GCR images for application jar
#
images:
<<<<<<< Updated upstream
  - 'gcr.io/$PROJECT_ID/pg45:latest'
=======
  - 'gcr.io/$PROJECT_ID/pg4:latest'
>>>>>>> Stashed changes

# Build timeout
timeout: 1800s
