steps:
#- name: 'ubuntu:trusty'
- name: 'gcr.io/spinnaker-terraform/postgres'
  #env: ['POSTGRES_PASSWORD=test1234']
  entrypoint: 'bash'
  #args: ['bash', 'workspace/postgres.sh']
  args: ['postgres.sh']

logsBucket: 'gs://cloud_builds'
